name: Build

on:
  pull_request:
  push:
    branches:
      - main
      - "keila/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
      - uses: gradle/actions/setup-gradle@v6
      - name: Configure git identity for paperweight
        run: |
          git config --global user.name "keila-ci"
          git config --global user.email "ci@tame.gg"
      - name: Apply patches
        run: ./gradlew applyAllPatches --stacktrace
      - name: Check
        run: ./gradlew check --stacktrace
      - name: Build paperclip jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace
